---
- name: My setup script
  gather_facts: yes
  hosts: local
  tasks:
    - name: Install Tmux
      become: "{{ ansible_os_family != 'Darwin' }}"
      package:
        name: tmux
        state: present
    - name: Check tmux config file exists
      stat:
        path: ~/.tmux.conf
      register: tmux_config_file
    - name: Create tmux config
      copy:
        src: ../config/.tmux.conf
        dest: ~/.tmux.conf
      when: not tmux_config_file.stat.exists
    - name: Install Neovim
      become: "{{ ansible_os_family != 'Darwin' }}"
      package:
        name: neovim 
        state: present

